### ISSUE TITLE
[VS-Clang] Tile lookup doesn't update ingame

### ISSUE THREAD

**Issue by tsunamistate** [afwbkbc/glsmac#6] opened 2023-02-12 12:58 UTC
OS: Windows 11
IDE: Visual Studio 2022 17.4.4
Compiler: Clang 15.0.1
System specs: AMD Ryzen 2600X / Radeon RX590 / 16 GB RAM

Steps to reproduce:

1. Open Visual Studio and open `glsmac` folder with it. Wait until CMake configuration finishes
2. Use `Build -> Build All` or `Ctrl+Shift+B` shortcut to compile an executable
3. Open a shell (Powershell or CMD) and navigate to executable's path: `<project root>\out\build\x64-debug-win-clang\bin`
4. Start a command to execute GLSMAC with game path `GLSMAC.exe <smac_directory>`
5. Click `Quick Start` to generate a map
6. Click on any tile

Actual result:
Debug console has messages like `<Task::World::#40537> Looking up tile at 261x442` but game UI doesn't update with tile information

https://user-images.githubusercontent.com/4958520/218312322-d006f644-bafa-4dc7-baa7-5790282e88cd.mp4

Expected result:
Game UI shows tile information after clicking on it

**Comment by afwbkbc** [comment] 2023-02-12 21:08
So far I couldn't reproduce it. I tried on 3 different PCs with different GPUs (Nvidia GTX1070, Radeon R7 and Intel 4500U), tile selection works correctly. All of them run Linux, tho. I also compiled windows version inside VirtualBox, then managed to run it on Radeon R7 computer through wine, and tile selection worked too.
I'll try to get some Windows computer next week.

**Comment by hartmark** [comment] 2023-02-12 22:26
I'm on archlinux with AMD gpu and it seems to work for me too

**Comment by afwbkbc** [comment] 2023-02-12 23:00
I fixed some FBO-related code just now, give it a try.

**Comment by afwbkbc** [comment] 2023-03-01 22:58
Finally fixed in 9a94b60775476310d14a101fb553ea4ed70e684d + c1b34952b23a13d7bb88eee2c3c8d066ee8ec128, ty schombert for pointing me in right direction :)

**Closed by afwbkbc** 2023-03-01 22:58 UTC
Labels: bug
